
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\USER\git rep\CashierAndForecasting\build new\assets\frame11")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


windowW = Tk()

windowW.geometry("1280x720")
windowW.configure(bg = "#E8DFCA")


canvas = Canvas(
    windowW,
    bg = "#E8DFCA",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    5.0,
    1280.0,
    98.0,
    fill="#4F6F52",
    outline="")

canvas.create_text(
    512.0,
    17.0,
    anchor="nw",
    text="M E N U",
    fill="#FFFFFF",
    font=("IstokWeb Bold", 40 * -1)
)

canvas.create_rectangle(
    51.0,
    125.0,
    235.0,
    347.0,
    fill="#F5EFE6",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    109.0,
    327.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=79.0,
    y=317.0,
    width=60.0,
    height=18.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=173.666748046875,
    y=315.8039245605469,
    width=36.372093200683594,
    height=20.3137264251709
)

canvas.create_text(
    80.0,
    286.0,
    anchor="nw",
    text="Americano",
    fill="#000000",
    font=("IstokWeb Bold", 20 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    144.0,
    208.0,
    image=image_image_1
)

canvas.create_rectangle(
    301.0,
    125.0,
    488.0,
    347.0,
    fill="#F5EFE6",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    359.5,
    327.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=329.0,
    y=317.0,
    width=61.0,
    height=18.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=425.6666259765625,
    y=315.8039245605469,
    width=36.96511459350586,
    height=20.313724517822266
)

canvas.create_text(
    350.0,
    286.0,
    anchor="nw",
    text="Espresso",
    fill="#000000",
    font=("IstokWeb Bold", 20 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    395.0,
    214.0,
    image=image_image_2
)

canvas.create_rectangle(
    547.0,
    128.0,
    733.0,
    347.0,
    fill="#F5EFE6",
    outline="")

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    605.5,
    327.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=575.0,
    y=317.0,
    width=61.0,
    height=18.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=671.0,
    y=316.2254943847656,
    width=36.76744079589844,
    height=20.039215087890625
)

canvas.create_text(
    610.0,
    287.0,
    anchor="nw",
    text="Latte",
    fill="#000000",
    font=("IstokWeb Bold", 20 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    641.0,
    215.0,
    image=image_image_3
)

canvas.create_rectangle(
    792.0,
    128.0,
    981.0,
    347.0,
    fill="#F5EFE6",
    outline="")

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    851.5,
    327.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=820.0,
    y=317.0,
    width=63.0,
    height=18.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=918.6666259765625,
    y=316.2254943847656,
    width=37.558135986328125,
    height=20.039216995239258
)

canvas.create_text(
    830.0,
    287.0,
    anchor="nw",
    text="Cappuccino",
    fill="#000000",
    font=("IstokWeb Bold", 20 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    887.0,
    216.0,
    image=image_image_4
)

canvas.create_rectangle(
    1040.0,
    125.0,
    1222.0,
    347.0,
    fill="#F5EFE6",
    outline="")

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    1132.0,
    208.0,
    image=image_image_5
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    1097.0,
    327.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=1067.0,
    y=317.0,
    width=60.0,
    height=19.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=1161.33349609375,
    y=315.8039245605469,
    width=35.97674560546875,
    height=20.3137264251709
)

canvas.create_text(
    1080.0,
    286.0,
    anchor="nw",
    text="Cold Brew",
    fill="#000000",
    font=("IstokWeb Bold", 20 * -1)
)

canvas.create_rectangle(
    1038.0,
    411.0,
    1220.0,
    641.0,
    fill="#F5EFE6",
    outline="")

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    1095.0,
    619.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=1065.0,
    y=609.0,
    width=60.0,
    height=19.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=1159.33349609375,
    y=608.6797485351562,
    width=35.97674560546875,
    height=21.045751571655273
)

canvas.create_text(
    1080.0,
    578.0,
    anchor="nw",
    text="Mocha Latte",
    fill="#000000",
    font=("IstokWeb Bold", 20 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    1130.0,
    497.0,
    image=image_image_6
)

canvas.create_rectangle(
    792.0,
    411.0,
    989.0,
    641.0,
    fill="#F5EFE6",
    outline="")

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    853.5,
    619.5,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=821.0,
    y=609.0,
    width=65.0,
    height=19.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=923.333251953125,
    y=608.6797485351562,
    width=38.94186019897461,
    height=21.045751571655273
)

canvas.create_text(
    840.0,
    578.0,
    anchor="nw",
    text="Vanilla Latte",
    fill="#000000",
    font=("IstokWeb Bold", 20 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    891.0,
    497.0,
    image=image_image_7
)

canvas.create_rectangle(
    547.0,
    413.0,
    733.0,
    641.0,
    fill="#F5EFE6",
    outline="")

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    605.5,
    620.0,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=575.0,
    y=610.0,
    width=61.0,
    height=18.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=671.0001220703125,
    y=608.9607543945312,
    width=36.7674446105957,
    height=20.86274528503418
)

canvas.create_text(
    580.0,
    578.0,
    anchor="nw",
    text="Hazelnut Latte",
    fill="#000000",
    font=("IstokWeb Bold", 20 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    645.0,
    504.0,
    image=image_image_8
)

canvas.create_rectangle(
    297.0,
    411.0,
    494.0,
    641.0,
    fill="#F5EFE6",
    outline="")

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    396.0,
    503.0,
    image=image_image_9
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    359.0,
    619.5,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=327.0,
    y=609.0,
    width=64.0,
    height=19.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=428.3333740234375,
    y=608.6797485351562,
    width=38.94186019897461,
    height=21.045751571655273
)

canvas.create_text(
    360.0,
    578.0,
    anchor="nw",
    text="Thai Tea",
    fill="#000000",
    font=("Helvetica", 18 * -1)
)

canvas.create_rectangle(
    45.0,
    411.0,
    235.0,
    641.0,
    fill="#F5EFE6",
    outline="")

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    105.0,
    619.5,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=74.0,
    y=609.0,
    width=62.0,
    height=19.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=171.6666259765625,
    y=608.6797485351562,
    width=37.55813980102539,
    height=21.045751571655273
)

canvas.create_text(
    80.0,
    578.0,
    anchor="nw",
    text="Matcha Latte",
    fill="#000000",
    font=("IstokWeb Bold", 20 * -1)
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    141.0,
    503.0,
    image=image_image_10
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0, bg='#4F6F52',
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=1106.0,
    y=20.0,
    width=148.0,
    height=41.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12, bg='#4F6F52',
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat"
)
button_12.place(
    x=29.0,
    y=20.0,
    width=63.0,
    height=41.0
)
windowW.resizable(False, False)
windowW.mainloop()
